/* English. Same keys as de.js -- a test compares the two. */
const n = (count, one, many) => (count === 1 ? one : many);

export const en = {
  // General
  'allg.aendern': 'Change',
  'allg.freiwillig': 'optional',
  'allg.kopieren': 'Copy',
  'allg.kopiert': 'Copied.',
  'allg.speichern': 'Save',
  'allg.weiter': 'Continue',
  'allg.zurueck': 'Back',

  'fehler.allgemein': 'That did not work.',
  'fehler.keineVerbindung': 'No connection to the program.',
  'fehler.knotenAus': 'The node is not running.',
  'fehler.knotenStart': 'The node could not start: {0}',
  'fehler.kopieren': 'Copying did not work.',

  'zeit.tageStd': (d, h) => `${d} ${n(d, 'day', 'days')} ${h} h`,
  'zeit.stdMin': (h, m) => `${h} h ${m} min`,
  'zeit.min': m => `${m} min`,
  'zeit.unterMinute': 'under 1 min',
  'zeit.vorSek': s => (s < 5 ? 'just now' : `${s} seconds ago`),
  'zeit.vorMin': m => `${m} ${n(m, 'minute', 'minutes')} ago`,
  'zeit.vorStd': h => `${h} ${n(h, 'hour', 'hours')} ago`,
  'zeit.vorTagen': d => `${d} ${n(d, 'day', 'days')} ago`,

  // Sidebar
  'nav.bereiche': 'Sections',
  'nav.uebersicht': 'Overview',
  'nav.mining': 'Mining',
  'nav.blockchain': 'Blockchain',
  'nav.peers': 'Peers',
  'nav.einstellungen': 'Settings',
  'leiste.laeuft': 'Node running',
  'leiste.sync': 'Syncing',
  'leiste.gestoppt': 'Node stopped',
  'leiste.keineAntwort': 'No response',
  'leiste.zeile': (net, height, peers) => `${net} · height ${height} · ${peers} ${n(peers, 'peer', 'peers')}`,

  // Overview
  'ueb.titel': 'Overview',
  'ueb.sub': 'Your node verifies every block itself and passes it on to others.',
  'ueb.synchron': 'In sync',
  'ueb.synct': 'Syncing',
  'ueb.gestoppt': 'Stopped',
  'ueb.stoppen': 'Stop node',
  'ueb.starten': 'Start node',
  'ueb.kennzahlen': 'Key figures',
  'ueb.hoehe': 'Block height',
  'ueb.letzterBlock': 'last block {0}',
  'ueb.nochKeiner': 'no block yet',
  'ueb.peers': 'Peers',
  'ueb.ausEin': '{0} outbound · {1} inbound',
  'ueb.netz': 'Network hashrate',
  'ueb.netzSub': 'estimated from the difficulty',
  'ueb.belohnung': 'Reward per block',
  'ueb.halbierung': 'Halving at height {0}',
  'ueb.sync': 'Synchronisation',
  'ueb.aktuell': '100 % · level with the network',
  'ueb.wartePeer': 'waiting for a peer',
  'ueb.offen': '{0} blocks to go · {1} %',
  'ueb.geprueft': 'Blocks verified by this node',
  'ueb.wartend': 'Pending transfers',
  'ueb.difficulty': 'Difficulty',
  'ueb.wurzel': 'State root',
  'ueb.seit': 'Running for',
  'ueb.zumMining': 'Go to mining',
  'ueb.letzte': 'Latest blocks',
  'ueb.alle': 'View all',

  // Blockchain
  'kette.titel': 'Blockchain',
  'kette.sub': 'Your node has recomputed every one of these blocks itself.',
  'kette.suche': 'Search',
  'kette.suchfeld': 'Height, hash or address',
  'kette.suchen': 'Search',
  'kette.nichtsGefunden': 'There is no block, transfer or address matching that.',
  'kette.bloecke': 'Blocks',
  'kette.hoehe': 'Height',
  'kette.zeit': 'Time',
  'kette.gefunden': 'Found by',
  'kette.ueberweisungen': 'Transfers',
  'kette.ueberwKurz': 'Transf.',
  'kette.keine': 'No blocks yet.',
  'kette.bereich': 'Blocks {0} to {1} of {2}',
  'kette.neuere': 'Newer',
  'kette.aeltere': 'Older',
  'kette.pool': 'Pool',
  'kette.solo': 'Solo',
  'kette.empfaenger': e => `${e} ${n(e, 'recipient', 'recipients')}`,
  'kette.block': 'Block {0}',
  'kette.neuester': 'latest block',
  'kette.hashKopieren': 'Copy hash',
  'kette.adresseKopieren': 'Copy address',
  'kette.vorgaenger': 'Previous block',
  'kette.groesse': 'Size',
  'kette.byte': '{0} bytes',
  'kette.belohnung': 'Reward',
  'kette.gebuehren': 'fees',
  'kette.gehtAnEine': 'Reward goes to',
  'kette.gehtAn': a => `Reward goes to ${a} addresses`,
  'kette.nUeberweisungen': a => `${a} ${n(a, 'transfer', 'transfers')}`,
  'kette.adresse': 'Address',
  'kette.konto': 'Account',
  'kette.guthaben': 'Balance',
  'kette.gesendet': 'Transfers sent',
  'kette.soloBloecke': 'Blocks found solo',
  'kette.poolAnteile': 'Blocks with a pool share',
  'kette.verlauf': 'History',
  'kette.keinVerlauf': 'Nothing has happened yet.',
  'kette.art.reward': 'Block found',
  'kette.art.pool': 'Pool share',
  'kette.art.in': 'received from',
  'kette.art.out': 'sent to',
  'kette.ueberweisung': 'Transfer',
  'kette.unterwegs': 'pending',
  'kette.bestaetigt': 'confirmed',
  'kette.imBlock': 'In block',
  'kette.von': 'From',
  'kette.an': 'To',
  'kette.betrag': 'Amount',
  'kette.gebuehr': 'Fee',
  'kette.wartetSeit': 'Waiting since',
  'kette.wartend': 'Pending transfers',
  'kette.wartendText': a => `${a} ${n(a, 'is', 'are')} waiting for the next block · your node relays them to all peers`,
  'kette.wartendLeer': 'nothing waiting',
  'kette.wartendKeine': 'No transfer is waiting right now.',

  // Peers
  'peers.titel': 'Peers',
  'peers.sub': 'Your node exchanges blocks and transfers with these nodes.',
  'peers.vonAussen': 'reachable from outside',
  'peers.nurAus': 'outbound only',
  'peers.verbunden': 'Connected',
  'peers.hoechste': 'highest height {0}',
  'peers.keiner': 'nobody connected',
  'peers.ausgehend': 'Outbound',
  'peers.ausSub': 'opened by you',
  'peers.eingehend': 'Inbound',
  'peers.einSub': 'others found you',
  'peers.buch': 'Address book',
  'peers.buchSub': 'known nodes',
  'peers.liste': 'Connected nodes',
  'peers.adresse': 'Address',
  'peers.richtung': 'Direction',
  'peers.programm': 'Software',
  'peers.seit': 'Connected for',
  'peers.aktion': 'Action',
  'peers.aus': 'outbound',
  'peers.ein': 'inbound',
  'peers.trennen': 'Disconnect',
  'peers.keineVerbunden': 'Not connected to anyone yet.',
  'peers.hinzu': 'Add a peer',
  'peers.adressePort': 'Address and port',
  'peers.verbinden': 'Connect',
  'peers.wirdVerbunden': 'Connecting to {0}.',
  'peers.hinzuHinweis': 'You do not have to: your node finds further nodes on its own through the seed and its address book.',
  'peers.keinSeed': 'no seed entered',
  'peers.seedHinweis': 'The seed is only the first contact after start-up. If it is down, your node connects to the nodes in its address book.',
  'peers.erreichbarkeit': 'Reachability',
  'peers.offen': (a, port) => `${a} inbound ${n(a, 'connection', 'connections')}: port ${port} is open from outside.`,
  'peers.zu': 'No inbound connection so far. Port {0} is probably not reachable from outside.',
  'peers.erreichHinweis': 'Without port forwarding in the router the node still runs, with outbound connections only. With forwarding it helps others join the network.',

  // Mining
  'min.titel': 'Mining',
  'min.sub': 'Work on new blocks with your processor and graphics card.',
  'min.laeuft': 'running',
  'min.aus': 'off',
  'min.bereit': 'ready',
  'min.nichtBereit': 'not ready yet',
  'min.laeuftSeitChip': 'running for {0}',
  'min.starten': 'Start mining',
  'min.stoppen': 'Stop mining',
  'min.einstellungen': 'Settings',
  'min.gehtAn': 'Reward goes to',
  'min.gehtAnHinweis': 'Solo: if you find a block, the whole reward is yours. Until then there is nothing.',
  'min.geraet': 'Device',
  'min.ziel': 'Target',
  'min.solo': 'Solo',
  'min.cpu': 'Processor',
  'min.gpu': 'Graphics card',
  'min.beides': 'Both',
  'min.modus.cpu': 'Processor',
  'min.modus.gpu': 'Graphics card',
  'min.modus.beide': 'Processor and graphics card',
  'min.kerne': 'Cores',
  'min.kerneVon': '{0} of {1}',
  'min.nKerne': k => `${k} ${n(k, 'core', 'cores')}`,
  'min.last': 'Load per core',
  'min.lastHinweis': 'Less load keeps the PC cooler and quieter.',
  'min.karte': 'Card',
  'min.keineKarte': 'no card found',
  'min.nachbildung': 'emulation for testing',
  'min.cudaBereit': 'CUDA ready',
  'min.gpuFehlt': 'not available',
  'min.gpuSucht': 'searching',
  'min.gpuSuchen': 'Search again',
  'min.gpuHinweis': 'NVIDIA cards with CUDA are supported. Without a suitable card the processor works alone.',
  'min.letzterFehler': 'Last error: {0}',
  'min.name': 'Name in the block',
  'min.nameLeer': 'Leave empty: the explorer then shows "Unknown".',
  'min.nameZeichen': 'Plain characters only, no umlauts and no special characters.',
  'min.nameLang': 'At most 32 characters, currently {0}.',
  'min.nameKurz': 'At least three characters.',
  'min.nameBuchstabe': 'At least one letter or digit.',
  'min.nameOk': 'Shown publicly in the explorer for every block you find solo: {0} ({1} of 32 characters)',
  'min.gesperrt': 'Stop mining to change the settings.',
  'min.erwartung': 'What to expect',
  'min.deine': 'Your hashrate',
  'min.gemessen': 'measured right now',
  'min.nochNicht': 'not running yet',
  'min.schaetzung': 'At this hashrate you find a block about every {0} on average. That is an average, not a promise. It can be faster or take much longer.',
  'min.schaetzungOhne': 'Once mining is running, this shows how often you find a block on average.',
  'min.messwerte': 'Measurements',
  'min.leistung': 'Hashrate',
  'min.fehler': 'Errors',
  'min.arbeitetAn': 'Working on',
  'min.laeuftSeit': 'Running for',
  'min.funde': 'Blocks found by you',
  'min.fundeZahl': a => `solo · ${a} so far`,
  'min.fundeKeine': 'No block found solo yet.',
  'min.fundeOhneAdresse': 'Enter an address and its finds appear here.',

  // Settings
  'einst.titel': 'Settings',
  'einst.sub': 'The defaults suit most people. You do not have to change anything here.',
  'einst.knoten': 'Node',
  'einst.ordner': 'Data folder',
  'einst.ordnerHinweis': 'The blockchain is stored here.',
  'einst.apiPort': 'Node API port',
  'einst.apiHinweis': 'reachable on this PC only',
  'einst.p2pPort': 'P2P port',
  'einst.p2pHinweis': 'for connections to other nodes',
  'einst.seedHinweis': 'The first contact into the network. After that your node finds further nodes on its own.',
  'einst.geltenNach': 'Folder, ports and seed apply after the node has been restarted.',
  'einst.gespeichert': 'Saved.',
  'einst.neustartNoetig': 'Saved. The new values apply once the node has been restarted.',
  'einst.neuStarten': 'Restart node',
  'einst.neuGestartet': 'The node is running with the new values.',
  'einst.programmTitel': 'Program',
  'einst.knotenSofort': 'Start the node as soon as the program opens',
  'einst.knotenSofortHinweis': 'Otherwise you start it by hand in the overview.',
  'einst.sprache': 'Language',
  'einst.protokoll': 'Log',
  'einst.ueber': 'About',
  'einst.programm': 'Program',
  'einst.netz': 'Network',
  'einst.regeln': 'Rules',
  'einst.fassung': 'Consensus revision {0}',
  'einst.quelltext': 'Source code',

  // First start
  'einr.schritte': 'Steps',
  'einr.s1': 'Node',
  'einr.s3': 'Start',
  'einr.titel': 'Your own YSKAR node',
  'einr.einleitung': 'Node Core downloads the blockchain to this PC and verifies every block itself. You do not have to trust anyone. The defaults suit most people, you can simply click Continue.',
  'einr.ordnerHinweis': 'The blockchain is stored here. It is still small and grows with every block.',
  'einr.firewall': 'On first start Windows asks whether Node Core may access the network. Allow it, otherwise the node cannot find other nodes.',
  'einr.bereit': 'Ready to start',
  'einr.bereitText': 'The node starts on {0}, connects to the network and downloads the blockchain.',
  'einr.starten': 'Start node',

  // ---------------------------------------------------------------- Wallet
  'allg.abbrechen': 'Cancel',
  'zeit.heute': 'Today',
  'zeit.gestern': 'Yesterday',
  'zeit.heuteKurz': 'today',
  'nav.wallet': 'Wallet',
  'kette.du': 'you',
  'einr.s2': 'Wallet',
  'einr.walletDa': 'There is already a wallet on this PC. It stays as it is.',
  'einr.walletSpaeter': 'to be set up later',
  'min.meineWallet': 'My wallet',
  'min.andere': 'Another address',
  'ueb.oeffnen': 'Open',
  'ueb.walletFehlt': 'No wallet on this PC yet. Your mining rewards go into the wallet.',
  'ueb.walletGesperrt': 'Unlock to see balance and history.',

  'wal.titel': 'Wallet',
  'wal.sub': 'Your YSR on this PC. The key never leaves the device.',
  'wal.bereiche': 'Wallet sections',
  'wal.rUebersicht': 'Overview',
  'wal.rSenden': 'Send',
  'wal.rEmpfangen': 'Receive and contacts',
  'wal.rSicherung': 'Backup',
  'wal.sperren': 'Lock',
  'wal.entsperrt': 'unlocked',
  'wal.entsperrtRest': m => `unlocked · locks in ${m} min`,
  'wal.gesperrt': 'locked',

  'wal.einrichten': 'Set up wallet',
  'wal.einrichtenText': 'Your mining rewards go into the wallet. From here you send and receive YSR.',
  'wal.art': 'Kind of setup',
  'wal.neu': 'New wallet',
  'wal.neuText': 'You get 12 new words.',
  'wal.alt': 'Existing wallet',
  'wal.altText': 'With the 12 words from the app.',
  'wal.spaeter': 'Later',
  'wal.spaeterText': 'Just run the node.',
  'wal.spaeterLang': 'The node also runs without a wallet. You can set one up at any time under "Wallet". For mining you then need an address from elsewhere, for example from the app.',
  'wal.deine12': 'Your 12 words',
  'wal.die12': 'The 12 words',
  'wal.woerterWarnung': 'Write the words on paper in this order. They are the only way back to your balance. Nobody can restore them for you.',
  'wal.woerterPlatz': 'twelve words, separated by spaces',
  'wal.woerterZahl': n => `${n} of 12 words`,
  'wal.notiert': 'I have written the 12 words down on paper.',
  'wal.erstNotieren': 'First confirm that you have written down the 12 words.',
  'wal.anlegen': 'Create wallet',
  'wal.wiederherstellen': 'Restore wallet',
  'wal.passwort': 'Password',
  'wal.pwFuerPc': 'Password for this PC',
  'wal.pwNeu': 'New password',
  'wal.pwWiederholen': 'Repeat password',
  'wal.pwRegel': 'At least {0} characters. The longer, the better.',
  'wal.pwKurz': 'Too short: {0} of at least {1} characters.',
  'wal.pwGeht': '{0} characters. Longer would be better.',
  'wal.pwGut': 'good · {0} characters',
  'wal.pwUngleich': 'The two passwords do not match.',

  'wal.gesperrtTitel': 'Wallet locked',
  'wal.gesperrtText': 'Enter your password to see balance and history and to send.',
  'wal.entsperren': 'Unlock',
  'wal.vergessen': 'Forgot your password? Set a new one with the 12 words',
  'wal.vergessenTitel': 'Set a new password',
  'wal.vergessenText': 'Enter the 12 words of this wallet and choose a new password. Other words will not work.',
  'wal.pwSetzen': 'Set password',
  'wal.gesperrtHinweis': 'Node and mining keep running while the wallet is locked. For mining the program only needs your address, not your key. Rewards still arrive.',

  'wal.guthaben': 'Balance',
  'wal.heute': 'today',
  'wal.unterwegs': 'pending',
  'wal.verfuegbar': 'available',
  'wal.adresseKopieren': 'Copy address',
  'wal.empfangen': 'Receive',
  'wal.kontakte': 'Contacts',
  'wal.einnahmen': 'Mining income',
  'wal.sieben': 'last 7 days',
  'wal.ausBloecken': b => `YSR from ${b} ${b === 1 ? 'block' : 'blocks'}`,
  'wal.filter': 'Filter',
  'wal.fAlle': 'All',
  'wal.fEin': 'Incoming',
  'wal.fAus': 'Outgoing',
  'wal.suchfeld': 'Name, address or note',
  'wal.mehr': 'Show older',
  'wal.ausKnoten': 'The history comes from your own node, not from a server.',
  'wal.nochNichts': 'Nothing has happened yet. As soon as something arrives or you send, it appears here.',
  'wal.nichtsPassend': 'No entry matches that.',
  'wal.miningPool': 'Pool mining',
  'wal.miningSolo': 'Solo mining',
  'wal.anteileAus': b => `shares from ${b} ${b === 1 ? 'block' : 'blocks'}`,
  'wal.soloGefunden': b => `${b} ${b === 1 ? 'block' : 'blocks'} found solo`,
  'wal.zuletztBlock': 'latest block {0}',
  'wal.gesendetAn': 'Sent to {0}',
  'wal.empfangenVon': 'Received from {0}',
  'wal.wartetBlock': 'waiting for the next block',
  'wal.notizZeile': 'Note: {0}',
  'wal.gebuehrZeile': 'fee {0}',

  'wal.ueberweisung': 'Transfer',
  'wal.sEmpfaenger': 'Recipient',
  'wal.sBetrag': 'Amount',
  'wal.sPruefen': 'Review',
  'wal.sGesendet': 'Sent',
  'wal.empfaenger': 'Recipient',
  'wal.kontaktWaehlen': 'Choose contact',
  'wal.keineKontakte': 'no contacts',
  'wal.alles': 'Max',
  'wal.verfuegbarZeile': 'Available: {0} YSR',
  'wal.notiz': 'Note',
  'wal.notizHinweis': n => `Stored publicly in the blockchain, the recipient sees it too. ${n} of 32 bytes.`,
  'wal.tempo': 'Speed',
  'wal.langsam': 'slow',
  'wal.normal': 'normal',
  'wal.schnell': 'fast',
  'wal.tempoHinweis': 'The network is busy right now. Paying more gets you into a block sooner.',
  'wal.pruefen': 'Review',
  'wal.pruefenTitel': 'Review and send',
  'wal.pruefenLeer': 'Enter recipient and amount on the left and click Review. Nothing is sent without your password.',
  'wal.anAdresse': 'To this address',
  'wal.anName': 'To {0}',
  'wal.neueAdresse': 'New address.',
  'wal.neueAdresseText': 'You have never sent there before. Compare it character by character with the address you were given.',
  'wal.netzgebuehr': 'Network fee',
  'wal.naechsterBlock': 'next block',
  'wal.inBloecken': b => `in about ${b} blocks`,
  'wal.gesamt': 'Total',
  'wal.danach': 'Available afterwards',
  'wal.jetztSenden': 'Send now',
  'wal.endgueltig': 'A transfer cannot be taken back. Your node passes it straight to the network.',
  'wal.gesendetTitel': 'Sent',
  'wal.gesendetText': p => `The transfer is on its way and was announced to ${p} ${p === 1 ? 'peer' : 'peers'}. It is confirmed with the next block.`,
  'wal.zurUebersicht': 'Back to overview',
  'wal.weitere': 'Another transfer',

  'wal.qrAlt': 'QR code with your address',
  'wal.deineAdresse': 'Your address',
  'wal.adresseHinweis': 'You may give this address to anyone. It is the same as in the YSKAR app if you use the same 12 words there.',
  'wal.anfordern': 'Request an amount',
  'wal.anfordernHinweis': 'The QR code then contains address and amount. Whoever scans it with the app does not have to type anything.',
  'wal.kGespeichert': k => `${k} saved · on this PC only`,
  'wal.kKeine': 'No contacts yet. A contact is a name for an address.',
  'wal.kBearbeiten': 'Edit',
  'wal.kEntfernen': 'Remove contact {0}',
  'wal.kHinzu': 'Add a contact',
  'wal.kName': 'Name',
  'wal.kNamePlatz': 'for example Mara',
  'wal.kGespeichertMeldung': 'Contact saved.',

  'wal.die12Text': 'The 12 words are your wallet. If the PC is lost, you restore everything with them.',
  'wal.verdeckt': 'The 12 words, hidden',
  'wal.woerterZeigen': 'Show words',
  'wal.woerterVerdecken': 'Hide words',
  'wal.woerterGeheim': 'Whoever knows the 12 words can spend your balance. Write them on paper. No photo, no cloud, and never give them to anyone who asks.',
  'wal.inApp': 'The same wallet in the app',
  'wal.inAppText': 'With the same 12 words you also open this wallet in the YSKAR app on your phone. The balance is in the blockchain, not in a program. Both therefore show the same state.',
  'wal.pwAendern': 'Change password',
  'wal.pwAktuell': 'Current password',
  'wal.pwAendernHinweis': 'The password protects the wallet file on this PC. It does not replace the 12 words.',
  'wal.pwGeaendert': 'The password has been changed.',
  'wal.sperre': 'Lock',
  'wal.sperreNach': 'Lock automatically after',
  'wal.minuten': m => `${m} minutes`,
  'wal.nie': 'never',
  'wal.pwVorSenden': 'Password before every transfer',
  'wal.pwVorSendenHinweis': 'Even while the wallet is unlocked.',
  'wal.immerAn': 'always on',
  'wal.datei': 'Wallet file',
  'wal.dateiHinweis': 'Encrypted with AES-256-GCM. The key is derived from your password (PBKDF2, 400,000 rounds). The longer the password, the better the protection.',
  'wal.entfernenText': 'Removes the wallet from this PC. The balance stays in the blockchain and can be reached again with the 12 words. Without the words it is lost.',
  'wal.entfernen': 'Remove wallet',
  // Pool mining
  'pool.pool': 'Pool',
  'pool.hinweis': 'Pool: The reward of every block is split by the work done and paid out directly in the block. Smaller amounts, but regular.',
  'pool.waehlen': 'Choose a pool',
  'pool.listeHinweis': 'the same list as in the app',
  'pool.laedt': 'Asking the pools …',
  'pool.listeLeer': 'The pool list is not available right now.',
  'pool.eigen': 'Your own pool address',
  'pool.hier': 'Your pool on this PC',
  'pool.eigenKurz': 'own address',
  'pool.pruefen': 'Check',
  'pool.eigenUngueltig': 'That is not a pool address. Example: pool.example.org',
  'pool.gewaehlt': 'selected',
  'pool.voll': 'full',
  'pool.aus': 'not responding',
  'pool.keinPool': 'no pool',
  'pool.ausText': 'Nobody is answering at this address right now.',
  'pool.keinPoolText': 'No pool is running at this address.',
  'pool.ohneZahlen': 'Older version: the pool reports no numbers. Whether it accepts you shows when you start.',
  'pool.miner': 'Miners',
  'pool.bloecke': 'Blocks',
  'pool.gebuehr': 'Fee',
  'pool.belegtAlt': '{0} of {1} places taken',
  'pool.verbindung': 'Connection to the pool',
  'pool.verbunden': 'connected',
  'pool.gestoert': 'connection trouble',
  'pool.getrennt': 'not connected',
  'pool.minerImPool': 'Miners in the pool',
  'pool.angenommen': 'Accepted shares',
  'pool.abgelehnt': 'Rejected shares',
  'pool.anteil': 'Your part of the hashrate',
  'pool.rund': 'about {0} %',
  'pool.auszahlung': 'Last payout',
  'pool.fehlerZuletzt': 'Latest: {0}',
  'pool.nieSolo': 'If the pool is full or no longer accepts you, mining stops and tells you why. It never silently continues solo.',
  'pool.gesamtSeit': 'Total, for {0}',
  'pool.verlaufLeer': 'The chart starts after the first measurements.',
  'pool.verlaufAlt': 'Hashrate over the last {0}, between {1} and {2}',
  'pool.vor': '{0} ago',
  'pool.jetzt': 'now',
  'pool.endeTitel': 'Mining in the pool {0} has ended.',
  'pool.ende.pool_full': 'The pool is full: all places are taken.',
  'pool.ende.pool_unavailable': 'The node no longer runs a pool.',
  'pool.ende.bad_address': 'The pool does not accept this address.',
  'pool.fehler.pool_fehlt': 'Please choose a pool first.',
  'pool.fehler.pool_aus': 'The pool is not responding. Mining was not started.',
  'pool.fehler.pool_unavailable': 'No pool is running at this address.',
  'pool.fehler.pool_full': 'The pool is full: all places are taken. Choose another pool or try again later.',
  'pool.fehler.bad_address': 'The pool does not accept this address.',
  // Running a pool
  'nav.pool': 'Run a pool',
  'betr.titel': 'Run a pool',
  'betr.sub': 'Let others mine together through your node. Your node splits every reward itself.',
  'betr.aktiv': 'Pool active',
  'betr.laeuft': 'Pool running',
  'betr.aus': 'off',
  'betr.wartetAufKnoten': 'starts with the node',
  'betr.nichtGestartet': 'not started',
  'betr.kennzahlen': 'Key figures',
  'betr.frei': f => `${f} ${n(f, 'place', 'places')} free`,
  'betr.poolAus': 'The pool is not running.',
  'betr.leistung': 'Pool hashrate',
  'betr.vomNetz': 'about {0} % of the network',
  'betr.wirdGemessen': 'being measured',
  'betr.gemessen': 'measured from the shares',
  'betr.bloecke': 'Blocks found',
  'betr.zuletzt': 'latest: block {0}',
  'betr.zaehlt': 'counting …',
  'betr.nochKeiner': 'none yet',
  'betr.gebuehr': 'Your fee',
  'betr.jeBlock': '{0} YSR per block',
  'betr.keineGebuehr': 'You take no fee.',
  'betr.name': 'Name of the pool',
  'betr.nameFehlt': 'The pool needs a name.',
  'betr.nameHinweis': 'Shown publicly in every block your pool finds. At most 32 simple characters.',
  'betr.gebuehrHinweis': 'At most 5 %. A change applies from the next block and is shown to the miners beforehand.',
  'betr.gebuehrBald': 'From the next block: {0}. Until then {1} applies.',
  'betr.gehtAn': 'Fee goes to',
  'betr.keineWallet': 'No wallet on this PC yet.',
  'betr.walletAnlegen': 'Set up a wallet',
  'betr.plaetze': 'Places',
  'betr.plaetzeHinweis': 'A block can pay out at most 64 addresses. With a fee one place is yours, leaving 63.',
  'betr.geltenNach': 'Name and places apply after the pool restarts.',
  'betr.neustartNoetig': 'Name or places have changed. They apply once the pool restarts. The miners sign in again when it does.',
  'betr.neuStarten': 'Restart pool',
  'betr.neuGestartet': 'The pool is running with the new settings.',
  'betr.wer': 'Who can join',
  'betr.hier': 'This PC',
  'betr.hierText': 'Your own miner can work in the pool: choose “Pool” under Mining, your pool is listed first.',
  'betr.hierLaeuft': 'Your own miner is working in the pool.',
  'betr.hierAktiv': 'active',
  'betr.zumMining': 'Go to mining',
  'betr.heimnetz': 'Devices in your home network',
  'betr.heimnetzText': 'Other PCs in the same network can join with the command-line miner. Switched off, the pool is reachable from this PC only.',
  'betr.heimnetzWartet': 'Switched on. Sharing applies as soon as the pool is running.',
  'betr.heimnetzOffen': 'Other PCs with the command-line miner connect to this address. Windows asks the first time whether to allow access.',
  'betr.heimnetzKeine': 'This PC has no address in a home network right now.',
  'betr.internet': 'App and Mini App from the internet',
  'betr.internetText': 'They connect over HTTPS only. For that you need your own address on the internet with a certificate. Node Core does not set this up.',
  'betr.anleitung': 'Open the guide',
  'betr.selbst': 'set up yourself',
  'betr.liste': 'In the app’s pool list',
  'betr.listeText': 'Only possible once your pool is reachable over HTTPS. The list is maintained by hand.',
  'betr.listeAnfragen': 'Request listing',
  'betr.minerTitel': 'Miners in the pool',
  'betr.fenster': 'Work in the current window',
  'betr.anteil': 'Part',
  'betr.letzterShare': 'Latest share',
  'betr.nochKeinShare': 'none yet',
  'betr.niemand': 'Nobody in the pool yet.',
  'betr.weitere': w => `and ${w} more ${n(w, 'address', 'addresses')} with a smaller part`,
  'betr.fensterBleibt': 'Recent work is paid, across block finds. It is kept across a restart, too.',
  'betr.fehler.wallet_fehlt': 'For a fee the pool needs a wallet on this PC to receive it. Set up a wallet first or set the fee to 0 %.',
  // Program, updates, security
  'einst.waehlen': 'Choose',
  'einst.ordnerBelegt': 'In use: {0}.',
  'einst.ordnerOeffnen': 'Open folder',
  'einst.sicherheit': 'Security',
  'einst.sicherheitText': 'The interface is reachable from this PC only and protected by an access key. Websites in your browser cannot change anything on your node.',
  'einst.passwortSenden': 'Password before every transfer',
  'einst.immerAn': 'always on',
  'einst.autostart': 'Start with Windows',
  'einst.autostartHinweis': 'Starts without a window when you sign in. The icon sits in the notification area next to the clock.',
  'einst.autostartFenster': 'Starts when you sign in.',
  'einst.imHintergrund': 'Keep running when closed',
  'einst.imHintergrundHinweis': 'The window disappears into the notification area next to the clock, the node keeps working.',
  'einst.miningFortsetzen': 'Resume mining after start',
  'einst.miningFortsetzenHinweis': 'With the settings chosen last, as soon as the node is in sync. Only if mining was running when the program closed.',
  'einst.beendenText': 'Quit the program',
  'einst.beendenHinweis': 'Stops mining, pool and node and closes the program.',
  'einst.beenden': 'Quit',
  'einst.beendenSicher': 'Really quit?',
  'einst.beendet': 'Node Core is shutting down. You can close this window.',
  'einst.updates': 'Updates',
  'einst.installiert': 'Installed',
  'einst.neueste': 'Latest version',
  'einst.quelle': 'Source',
  'einst.updatesSuchen': 'Look for a new version at start',
  'einst.updatesSuchenHinweis': 'Asks GitHub once for that. Nothing else is transmitted.',
  'einst.updateHinweis': 'Nothing is installed by itself. You download the installer and run it.',
  'einst.jetztSuchen': 'Check now',
  'einst.herunterladen': 'Go to download',
  'einst.nochNieGesucht': 'Not checked yet.',
  'einst.suchFehler': 'The check did not work: {0}',
  'einst.neuDa': 'Version {0} is available.',
  'einst.aktuell': 'You have the latest version.',
  'einst.zuletztGesucht': 'Last checked {0}.',
  'einst.keineGefunden': 'There is no Node Core release on GitHub yet.',
  'leiste.neueVersion': 'Version {0} available',
  // Messages from the node, by code
  'srv.knoten_aus': 'Start the node first.',
  'srv.nicht_eingerichtet': 'The node has not been set up yet.',
  'srv.nicht_bereit': 'The node is not ready yet.',
  'srv.bereit_kein_peer': 'No peer connected yet. Without a connection to the network a found block would be worthless. Please wait a moment.',
  'srv.bereit_sync_hoehe': 'The node is still synchronising (height {0} of {1}). Mining starts once it has caught up with the network.',
  'srv.bereit_sync_bloecke': 'The node is still synchronising ({0} blocks missing). Mining starts once it has caught up with the network.',
  'srv.adresse_falsch': 'That is not a valid YSKAR address.',
  'srv.block_name': 'The name in the block is not allowed: plain characters only, 3 to 32.',
  'srv.gpu_nicht_moeglich': 'Mining with the graphics card is not possible: {0}',
  'srv.gpu_nicht_gestartet': 'The graphics card was not started: {0}',
  'srv.gpu_kein_programm': 'The program for the graphics card is not installed (yskar-cuda is missing).',
  'srv.gpu_nicht_startbar': 'The program for the graphics card cannot be started.',
  'srv.gpu_keine_antwort': 'The search for the graphics card did not respond.',
  'srv.gpu_keine_karte': 'No graphics card with CUDA found.',
  'srv.ohne_huelle': 'This only works in the installed program.',
  'srv.ordner_fehlt': 'The folder does not exist yet.',
  'srv.link_gesperrt': 'The program does not open this address.',
  'srv.datenordner_fehlt': 'The data folder is missing.',
  'srv.ordner_kein_ordner': 'The data folder is not a folder.',
  'srv.port_node': 'The node API port must be between 1024 and 65535.',
  'srv.port_p2p': 'The P2P port must be between 1024 and 65535.',
  'srv.ports_gleich': 'Node API port and P2P port must differ.',
  'srv.seed_format': 'The seed “{0}” must have the form host:port.',
  'srv.seed_port': 'The port of the seed is invalid.',
  'srv.peer_adresse': 'That is not the address of a node. Example: 203.0.113.9:8646',
  'srv.peer_weg': 'This connection no longer exists.',
  'srv.wallet_fehlt': 'For a fee the pool needs a wallet on this PC to receive it.',
  'srv.pool_fehlt': 'Please choose a pool first.',
  'srv.pool_aus': 'The pool is not responding.',
  'srv.pool_unavailable': 'No pool is running at this address.',
  'srv.pool_full': 'The pool is full: all places are taken.',
  'srv.bad_address': 'The pool does not accept this address.',
  'srv.pool_name_fehlt': 'The pool needs a name.',
  'srv.betrieb_name': 'The name of the pool is not allowed: plain characters only, 3 to 32.',
  'srv.betrieb_gebuehr': 'The fee is between 0 and 5 %, in steps of 0.25 %.',
  'srv.betrieb_plaetze': 'The number of places is between 1 and {0}.',
  'srv.heimnetz_fehler': 'Sharing in the home network is not possible: {0}',
  'srv.keine_wallet': 'No wallet has been set up yet.',
  'srv.gesperrt': 'The wallet is locked.',
  'srv.passwort_kurz': 'The password needs at least {0} characters.',
  'srv.passwort_lang': 'The password is too long.',
  'srv.passwort_falsch': 'The password is not correct.',
  'srv.pause': 'Too many wrong attempts. Please wait {0} seconds.',
  'srv.datei_beschaedigt': 'The wallet file does not match its words. It was changed or is damaged.',
  'srv.datei_unlesbar': 'wallet.json exists but cannot be read. Back up the file before you create a new wallet.',
  'srv.wallet_vorhanden': 'There is already a wallet on this PC. Remove it first.',
  'srv.woerter_falsch': 'These are not 12 valid words. Check spelling and order.',
  'srv.woerter_fremd': 'These 12 words belong to a different wallet than the one on this PC.',
  'srv.kontakt_name': 'The contact needs a name.',
  'srv.kontakt_name_lang': 'The name may have at most {0} characters.',
  'srv.kontakte_voll': 'No more contacts fit in.',
  'srv.senden_knoten_aus': 'The node must be running to send.',
  'srv.eigene_adresse': 'That is your own address.',
  'srv.guthaben_reicht_nicht': 'The balance is not enough for that.',
  'srv.betrag_falsch': 'Enter an amount.',
  'srv.betrag_staub': 'The amount is too small. At least 0.000001 YSR.',
  'srv.abgelehnt_insufficient_funds': 'The balance is not enough for that.',
  'srv.abgelehnt_fee_too_low': 'The fee is too low for the node.',
  'srv.abgelehnt_nonce_gap': 'An earlier transfer is still waiting. Please wait a moment and try again.',
  'srv.abgelehnt_nonce_too_low': 'An earlier transfer is still waiting. Please wait a moment and try again.',
  'srv.abgelehnt_unknown_account': 'There is no balance on this wallet yet.',
  'srv.abgelehnt_sender_limit': 'Too many transfers from this wallet are already waiting.',
  'srv.abgelehnt_pool_full': 'The node’s queue is full. Please try again later.',
  'srv.abgelehnt_duplicate': 'This transfer has already been submitted.',
};
