/* English. Same keys as de.js -- a test compares the two. */
const n = (count, one, many) => (count === 1 ? one : many);

export const en = {
  // General
  'allg.aendern': 'Change',
  'allg.freiwillig': 'optional',
  'allg.kopieren': 'Copy',
  'allg.kopiert': 'Copied.',
  'allg.speichern': 'Save',
  'allg.weiter': 'Continue',
  'allg.zurueck': 'Back',

  'fehler.allgemein': 'That did not work.',
  'fehler.keineVerbindung': 'No connection to the program.',
  'fehler.knotenAus': 'The node is not running.',
  'fehler.knotenStart': 'The node could not start: {0}',
  'fehler.kopieren': 'Copying did not work.',

  'zeit.tageStd': (d, h) => `${d} ${n(d, 'day', 'days')} ${h} h`,
  'zeit.stdMin': (h, m) => `${h} h ${m} min`,
  'zeit.min': m => `${m} min`,
  'zeit.unterMinute': 'under 1 min',
  'zeit.vorSek': s => (s < 5 ? 'just now' : `${s} seconds ago`),
  'zeit.vorMin': m => `${m} ${n(m, 'minute', 'minutes')} ago`,
  'zeit.vorStd': h => `${h} ${n(h, 'hour', 'hours')} ago`,
  'zeit.vorTagen': d => `${d} ${n(d, 'day', 'days')} ago`,

  // Sidebar
  'nav.bereiche': 'Sections',
  'nav.uebersicht': 'Overview',
  'nav.mining': 'Mining',
  'nav.blockchain': 'Blockchain',
  'nav.peers': 'Peers',
  'nav.einstellungen': 'Settings',
  'leiste.laeuft': 'Node running',
  'leiste.sync': 'Syncing',
  'leiste.gestoppt': 'Node stopped',
  'leiste.keineAntwort': 'No response',
  'leiste.zeile': (net, height, peers) => `${net} · height ${height} · ${peers} ${n(peers, 'peer', 'peers')}`,

  // Overview
  'ueb.titel': 'Overview',
  'ueb.sub': 'Your node verifies every block itself and passes it on to others.',
  'ueb.synchron': 'In sync',
  'ueb.synct': 'Syncing',
  'ueb.gestoppt': 'Stopped',
  'ueb.stoppen': 'Stop node',
  'ueb.starten': 'Start node',
  'ueb.kennzahlen': 'Key figures',
  'ueb.hoehe': 'Block height',
  'ueb.letzterBlock': 'last block {0}',
  'ueb.nochKeiner': 'no block yet',
  'ueb.peers': 'Peers',
  'ueb.ausEin': '{0} outbound · {1} inbound',
  'ueb.netz': 'Network hashrate',
  'ueb.netzSub': 'estimated from the difficulty',
  'ueb.belohnung': 'Reward per block',
  'ueb.halbierung': 'Halving at height {0}',
  'ueb.sync': 'Synchronisation',
  'ueb.aktuell': '100 % · level with the network',
  'ueb.wartePeer': 'waiting for a peer',
  'ueb.offen': '{0} blocks to go · {1} %',
  'ueb.geprueft': 'Blocks verified by this node',
  'ueb.wartend': 'Pending transfers',
  'ueb.difficulty': 'Difficulty',
  'ueb.wurzel': 'State root',
  'ueb.seit': 'Running for',
  'ueb.zumMining': 'Go to mining',
  'ueb.letzte': 'Latest blocks',
  'ueb.alle': 'View all',

  // Blockchain
  'kette.titel': 'Blockchain',
  'kette.sub': 'Your node has recomputed every one of these blocks itself.',
  'kette.suche': 'Search',
  'kette.suchfeld': 'Height, hash or address',
  'kette.suchen': 'Search',
  'kette.nichtsGefunden': 'There is no block, transfer or address matching that.',
  'kette.bloecke': 'Blocks',
  'kette.hoehe': 'Height',
  'kette.zeit': 'Time',
  'kette.gefunden': 'Found by',
  'kette.ueberweisungen': 'Transfers',
  'kette.ueberwKurz': 'Transf.',
  'kette.keine': 'No blocks yet.',
  'kette.bereich': 'Blocks {0} to {1} of {2}',
  'kette.neuere': 'Newer',
  'kette.aeltere': 'Older',
  'kette.pool': 'Pool',
  'kette.solo': 'Solo',
  'kette.empfaenger': e => `${e} ${n(e, 'recipient', 'recipients')}`,
  'kette.block': 'Block {0}',
  'kette.neuester': 'latest block',
  'kette.hashKopieren': 'Copy hash',
  'kette.adresseKopieren': 'Copy address',
  'kette.vorgaenger': 'Previous block',
  'kette.groesse': 'Size',
  'kette.byte': '{0} bytes',
  'kette.belohnung': 'Reward',
  'kette.gebuehren': 'fees',
  'kette.gehtAnEine': 'Reward goes to',
  'kette.gehtAn': a => `Reward goes to ${a} addresses`,
  'kette.nUeberweisungen': a => `${a} ${n(a, 'transfer', 'transfers')}`,
  'kette.adresse': 'Address',
  'kette.konto': 'Account',
  'kette.guthaben': 'Balance',
  'kette.gesendet': 'Transfers sent',
  'kette.soloBloecke': 'Blocks found solo',
  'kette.poolAnteile': 'Blocks with a pool share',
  'kette.verlauf': 'History',
  'kette.keinVerlauf': 'Nothing has happened yet.',
  'kette.art.reward': 'Block found',
  'kette.art.pool': 'Pool share',
  'kette.art.in': 'received from',
  'kette.art.out': 'sent to',
  'kette.ueberweisung': 'Transfer',
  'kette.unterwegs': 'pending',
  'kette.bestaetigt': 'confirmed',
  'kette.imBlock': 'In block',
  'kette.von': 'From',
  'kette.an': 'To',
  'kette.betrag': 'Amount',
  'kette.gebuehr': 'Fee',
  'kette.wartetSeit': 'Waiting since',
  'kette.wartend': 'Pending transfers',
  'kette.wartendText': a => `${a} ${n(a, 'is', 'are')} waiting for the next block · your node relays them to all peers`,
  'kette.wartendLeer': 'nothing waiting',
  'kette.wartendKeine': 'No transfer is waiting right now.',

  // Peers
  'peers.titel': 'Peers',
  'peers.sub': 'Your node exchanges blocks and transfers with these nodes.',
  'peers.vonAussen': 'reachable from outside',
  'peers.nurAus': 'outbound only',
  'peers.verbunden': 'Connected',
  'peers.hoechste': 'highest height {0}',
  'peers.keiner': 'nobody connected',
  'peers.ausgehend': 'Outbound',
  'peers.ausSub': 'opened by you',
  'peers.eingehend': 'Inbound',
  'peers.einSub': 'others found you',
  'peers.buch': 'Address book',
  'peers.buchSub': 'known nodes',
  'peers.liste': 'Connected nodes',
  'peers.adresse': 'Address',
  'peers.richtung': 'Direction',
  'peers.programm': 'Software',
  'peers.seit': 'Connected for',
  'peers.aktion': 'Action',
  'peers.aus': 'outbound',
  'peers.ein': 'inbound',
  'peers.trennen': 'Disconnect',
  'peers.keineVerbunden': 'Not connected to anyone yet.',
  'peers.hinzu': 'Add a peer',
  'peers.adressePort': 'Address and port',
  'peers.verbinden': 'Connect',
  'peers.wirdVerbunden': 'Connecting to {0}.',
  'peers.hinzuHinweis': 'You do not have to: your node finds further nodes on its own through the seed and its address book.',
  'peers.keinSeed': 'no seed entered',
  'peers.seedHinweis': 'The seed is only the first contact after start-up. If it is down, your node connects to the nodes in its address book.',
  'peers.erreichbarkeit': 'Reachability',
  'peers.offen': (a, port) => `${a} inbound ${n(a, 'connection', 'connections')}: port ${port} is open from outside.`,
  'peers.zu': 'No inbound connection so far. Port {0} is probably not reachable from outside.',
  'peers.erreichHinweis': 'Without port forwarding in the router the node still runs, with outbound connections only. With forwarding it helps others join the network.',

  // Mining
  'min.titel': 'Mining',
  'min.sub': 'Work on new blocks with your processor and graphics card.',
  'min.laeuft': 'running',
  'min.aus': 'off',
  'min.bereit': 'ready',
  'min.nichtBereit': 'not ready yet',
  'min.laeuftSeitChip': 'running for {0}',
  'min.starten': 'Start mining',
  'min.stoppen': 'Stop mining',
  'min.einstellungen': 'Settings',
  'min.gehtAn': 'Reward goes to',
  'min.gehtAnHinweis': 'Solo: if you find a block, the whole reward is yours. Until then there is nothing.',
  'min.geraet': 'Device',
  'min.ziel': 'Target',
  'min.solo': 'Solo',
  'min.cpu': 'Processor',
  'min.gpu': 'Graphics card',
  'min.beides': 'Both',
  'min.modus.cpu': 'Processor',
  'min.modus.gpu': 'Graphics card',
  'min.modus.beide': 'Processor and graphics card',
  'min.kerne': 'Cores',
  'min.kerneVon': '{0} of {1}',
  'min.nKerne': k => `${k} ${n(k, 'core', 'cores')}`,
  'min.last': 'Load per core',
  'min.lastHinweis': 'Less load keeps the PC cooler and quieter.',
  'min.karte': 'Card',
  'min.keineKarte': 'no card found',
  'min.nachbildung': 'emulation for testing',
  'min.cudaBereit': 'CUDA ready',
  'min.gpuFehlt': 'not available',
  'min.gpuSucht': 'searching',
  'min.gpuSuchen': 'Search again',
  'min.gpuHinweis': 'NVIDIA cards with CUDA are supported. Without a suitable card the processor works alone.',
  'min.letzterFehler': 'Last error: {0}',
  'min.name': 'Name in the block',
  'min.nameLeer': 'Leave empty: the explorer then shows "Unknown".',
  'min.nameZeichen': 'Plain characters only, no umlauts and no special characters.',
  'min.nameLang': 'At most 32 characters, currently {0}.',
  'min.nameKurz': 'At least three characters.',
  'min.nameBuchstabe': 'At least one letter or digit.',
  'min.nameOk': 'Shown publicly in the explorer for every block you find solo: {0} ({1} of 32 characters)',
  'min.gesperrt': 'Stop mining to change the settings.',
  'min.erwartung': 'What to expect',
  'min.deine': 'Your hashrate',
  'min.gemessen': 'measured right now',
  'min.nochNicht': 'not running yet',
  'min.schaetzung': 'At this hashrate you find a block about every {0} on average. That is an average, not a promise. It can be faster or take much longer.',
  'min.schaetzungOhne': 'Once mining is running, this shows how often you find a block on average.',
  'min.messwerte': 'Measurements',
  'min.leistung': 'Hashrate',
  'min.fehler': 'Errors',
  'min.arbeitetAn': 'Working on',
  'min.laeuftSeit': 'Running for',
  'min.funde': 'Blocks found by you',
  'min.fundeZahl': a => `solo · ${a} so far`,
  'min.fundeKeine': 'No block found solo yet.',
  'min.fundeOhneAdresse': 'Enter an address and its finds appear here.',

  // Settings
  'einst.titel': 'Settings',
  'einst.sub': 'The defaults suit most people. You do not have to change anything here.',
  'einst.knoten': 'Node',
  'einst.ordner': 'Data folder',
  'einst.ordnerHinweis': 'The blockchain is stored here.',
  'einst.apiPort': 'Node API port',
  'einst.apiHinweis': 'reachable on this PC only',
  'einst.p2pPort': 'P2P port',
  'einst.p2pHinweis': 'for connections to other nodes',
  'einst.seedHinweis': 'The first contact into the network. After that your node finds further nodes on its own.',
  'einst.geltenNach': 'Folder, ports and seed apply after the node has been restarted.',
  'einst.gespeichert': 'Saved.',
  'einst.neustartNoetig': 'Saved. The new values apply once the node has been restarted.',
  'einst.neuStarten': 'Restart node',
  'einst.neuGestartet': 'The node is running with the new values.',
  'einst.programmTitel': 'Program',
  'einst.knotenSofort': 'Start the node as soon as the program opens',
  'einst.knotenSofortHinweis': 'Otherwise you start it by hand in the overview.',
  'einst.sprache': 'Language',
  'einst.protokoll': 'Log',
  'einst.ueber': 'About',
  'einst.programm': 'Program',
  'einst.netz': 'Network',
  'einst.regeln': 'Rules',
  'einst.fassung': 'Consensus revision {0}',
  'einst.quelltext': 'Source code',

  // First start
  'einr.schritte': 'Steps',
  'einr.s1': 'Node',
  'einr.s3': 'Start',
  'einr.titel': 'Your own YSKAR node',
  'einr.einleitung': 'Node Core downloads the blockchain to this PC and verifies every block itself. You do not have to trust anyone. The defaults suit most people, you can simply click Continue.',
  'einr.ordnerHinweis': 'The blockchain is stored here. It is still small and grows with every block.',
  'einr.firewall': 'On first start Windows asks whether Node Core may access the network. Allow it, otherwise the node cannot find other nodes.',
  'einr.bereit': 'Ready to start',
  'einr.bereitText': 'The node starts on {0}, connects to the network and downloads the blockchain.',
  'einr.starten': 'Start node',
};
