/* English. Same keys as de.js -- a test compares the two. */
const n = (count, one, many) => (count === 1 ? one : many);

export const en = {
  // General
  'allg.aendern': 'Change',
  'allg.freiwillig': 'optional',
  'allg.kopieren': 'Copy',
  'allg.kopiert': 'Copied.',
  'allg.speichern': 'Save',
  'allg.weiter': 'Continue',
  'allg.zurueck': 'Back',

  'fehler.allgemein': 'That did not work.',
  'fehler.keineVerbindung': 'No connection to the program.',
  'fehler.knotenAus': 'The node is not running.',
  'fehler.knotenStart': 'The node could not start: {0}',
  'fehler.kopieren': 'Copying did not work.',

  'zeit.tageStd': (d, h) => `${d} ${n(d, 'day', 'days')} ${h} h`,
  'zeit.stdMin': (h, m) => `${h} h ${m} min`,
  'zeit.min': m => `${m} min`,
  'zeit.unterMinute': 'under 1 min',
  'zeit.vorSek': s => (s < 5 ? 'just now' : `${s} seconds ago`),
  'zeit.vorMin': m => `${m} ${n(m, 'minute', 'minutes')} ago`,
  'zeit.vorStd': h => `${h} ${n(h, 'hour', 'hours')} ago`,
  'zeit.vorTagen': d => `${d} ${n(d, 'day', 'days')} ago`,

  // Sidebar
  'nav.bereiche': 'Sections',
  'nav.uebersicht': 'Overview',
  'nav.mining': 'Mining',
  'nav.blockchain': 'Blockchain',
  'nav.peers': 'Peers',
  'nav.einstellungen': 'Settings',
  'leiste.laeuft': 'Node running',
  'leiste.sync': 'Syncing',
  'leiste.gestoppt': 'Node stopped',
  'leiste.keineAntwort': 'No response',
  'leiste.zeile': (net, height, peers) => `${net} · height ${height} · ${peers} ${n(peers, 'peer', 'peers')}`,

  // Overview
  'ueb.titel': 'Overview',
  'ueb.sub': 'Your node verifies every block itself and passes it on to others.',
  'ueb.synchron': 'In sync',
  'ueb.synct': 'Syncing',
  'ueb.gestoppt': 'Stopped',
  'ueb.stoppen': 'Stop node',
  'ueb.starten': 'Start node',
  'ueb.kennzahlen': 'Key figures',
  'ueb.hoehe': 'Block height',
  'ueb.letzterBlock': 'last block {0}',
  'ueb.nochKeiner': 'no block yet',
  'ueb.peers': 'Peers',
  'ueb.ausEin': '{0} outbound · {1} inbound',
  'ueb.netz': 'Network hashrate',
  'ueb.netzSub': 'estimated from the difficulty',
  'ueb.belohnung': 'Reward per block',
  'ueb.halbierung': 'Halving at height {0}',
  'ueb.sync': 'Synchronisation',
  'ueb.aktuell': '100 % · level with the network',
  'ueb.wartePeer': 'waiting for a peer',
  'ueb.offen': '{0} blocks to go · {1} %',
  'ueb.geprueft': 'Blocks verified by this node',
  'ueb.wartend': 'Pending transfers',
  'ueb.difficulty': 'Difficulty',
  'ueb.wurzel': 'State root',
  'ueb.seit': 'Running for',
  'ueb.zumMining': 'Go to mining',
  'ueb.letzte': 'Latest blocks',
  'ueb.alle': 'View all',

  // Blockchain
  'kette.titel': 'Blockchain',
  'kette.sub': 'Your node has recomputed every one of these blocks itself.',
  'kette.suche': 'Search',
  'kette.suchfeld': 'Height, hash or address',
  'kette.suchen': 'Search',
  'kette.nichtsGefunden': 'There is no block, transfer or address matching that.',
  'kette.bloecke': 'Blocks',
  'kette.hoehe': 'Height',
  'kette.zeit': 'Time',
  'kette.gefunden': 'Found by',
  'kette.ueberweisungen': 'Transfers',
  'kette.ueberwKurz': 'Transf.',
  'kette.keine': 'No blocks yet.',
  'kette.bereich': 'Blocks {0} to {1} of {2}',
  'kette.neuere': 'Newer',
  'kette.aeltere': 'Older',
  'kette.pool': 'Pool',
  'kette.solo': 'Solo',
  'kette.empfaenger': e => `${e} ${n(e, 'recipient', 'recipients')}`,
  'kette.block': 'Block {0}',
  'kette.neuester': 'latest block',
  'kette.hashKopieren': 'Copy hash',
  'kette.adresseKopieren': 'Copy address',
  'kette.vorgaenger': 'Previous block',
  'kette.groesse': 'Size',
  'kette.byte': '{0} bytes',
  'kette.belohnung': 'Reward',
  'kette.gebuehren': 'fees',
  'kette.gehtAnEine': 'Reward goes to',
  'kette.gehtAn': a => `Reward goes to ${a} addresses`,
  'kette.nUeberweisungen': a => `${a} ${n(a, 'transfer', 'transfers')}`,
  'kette.adresse': 'Address',
  'kette.konto': 'Account',
  'kette.guthaben': 'Balance',
  'kette.gesendet': 'Transfers sent',
  'kette.soloBloecke': 'Blocks found solo',
  'kette.poolAnteile': 'Blocks with a pool share',
  'kette.verlauf': 'History',
  'kette.keinVerlauf': 'Nothing has happened yet.',
  'kette.art.reward': 'Block found',
  'kette.art.pool': 'Pool share',
  'kette.art.in': 'received from',
  'kette.art.out': 'sent to',
  'kette.ueberweisung': 'Transfer',
  'kette.unterwegs': 'pending',
  'kette.bestaetigt': 'confirmed',
  'kette.imBlock': 'In block',
  'kette.von': 'From',
  'kette.an': 'To',
  'kette.betrag': 'Amount',
  'kette.gebuehr': 'Fee',
  'kette.wartetSeit': 'Waiting since',
  'kette.wartend': 'Pending transfers',
  'kette.wartendText': a => `${a} ${n(a, 'is', 'are')} waiting for the next block · your node relays them to all peers`,
  'kette.wartendLeer': 'nothing waiting',
  'kette.wartendKeine': 'No transfer is waiting right now.',

  // Peers
  'peers.titel': 'Peers',
  'peers.sub': 'Your node exchanges blocks and transfers with these nodes.',
  'peers.vonAussen': 'reachable from outside',
  'peers.nurAus': 'outbound only',
  'peers.verbunden': 'Connected',
  'peers.hoechste': 'highest height {0}',
  'peers.keiner': 'nobody connected',
  'peers.ausgehend': 'Outbound',
  'peers.ausSub': 'opened by you',
  'peers.eingehend': 'Inbound',
  'peers.einSub': 'others found you',
  'peers.buch': 'Address book',
  'peers.buchSub': 'known nodes',
  'peers.liste': 'Connected nodes',
  'peers.adresse': 'Address',
  'peers.richtung': 'Direction',
  'peers.programm': 'Software',
  'peers.seit': 'Connected for',
  'peers.aktion': 'Action',
  'peers.aus': 'outbound',
  'peers.ein': 'inbound',
  'peers.trennen': 'Disconnect',
  'peers.keineVerbunden': 'Not connected to anyone yet.',
  'peers.hinzu': 'Add a peer',
  'peers.adressePort': 'Address and port',
  'peers.verbinden': 'Connect',
  'peers.wirdVerbunden': 'Connecting to {0}.',
  'peers.hinzuHinweis': 'You do not have to: your node finds further nodes on its own through the seed and its address book.',
  'peers.keinSeed': 'no seed entered',
  'peers.seedHinweis': 'The seed is only the first contact after start-up. If it is down, your node connects to the nodes in its address book.',
  'peers.erreichbarkeit': 'Reachability',
  'peers.offen': (a, port) => `${a} inbound ${n(a, 'connection', 'connections')}: port ${port} is open from outside.`,
  'peers.zu': 'No inbound connection so far. Port {0} is probably not reachable from outside.',
  'peers.erreichHinweis': 'Without port forwarding in the router the node still runs, with outbound connections only. With forwarding it helps others join the network.',

  // Mining
  'min.titel': 'Mining',
  'min.sub': 'Work on new blocks with your processor and graphics card.',
  'min.laeuft': 'running',
  'min.aus': 'off',
  'min.bereit': 'ready',
  'min.nichtBereit': 'not ready yet',
  'min.laeuftSeitChip': 'running for {0}',
  'min.starten': 'Start mining',
  'min.stoppen': 'Stop mining',
  'min.einstellungen': 'Settings',
  'min.gehtAn': 'Reward goes to',
  'min.gehtAnHinweis': 'Solo: if you find a block, the whole reward is yours. Until then there is nothing.',
  'min.geraet': 'Device',
  'min.ziel': 'Target',
  'min.solo': 'Solo',
  'min.cpu': 'Processor',
  'min.gpu': 'Graphics card',
  'min.beides': 'Both',
  'min.modus.cpu': 'Processor',
  'min.modus.gpu': 'Graphics card',
  'min.modus.beide': 'Processor and graphics card',
  'min.kerne': 'Cores',
  'min.kerneVon': '{0} of {1}',
  'min.nKerne': k => `${k} ${n(k, 'core', 'cores')}`,
  'min.last': 'Load per core',
  'min.lastHinweis': 'Less load keeps the PC cooler and quieter.',
  'min.karte': 'Card',
  'min.keineKarte': 'no card found',
  'min.nachbildung': 'emulation for testing',
  'min.cudaBereit': 'CUDA ready',
  'min.gpuFehlt': 'not available',
  'min.gpuSucht': 'searching',
  'min.gpuSuchen': 'Search again',
  'min.gpuHinweis': 'NVIDIA cards with CUDA are supported. Without a suitable card the processor works alone.',
  'min.letzterFehler': 'Last error: {0}',
  'min.name': 'Name in the block',
  'min.nameLeer': 'Leave empty: the explorer then shows "Unknown".',
  'min.nameZeichen': 'Plain characters only, no umlauts and no special characters.',
  'min.nameLang': 'At most 32 characters, currently {0}.',
  'min.nameKurz': 'At least three characters.',
  'min.nameBuchstabe': 'At least one letter or digit.',
  'min.nameOk': 'Shown publicly in the explorer for every block you find solo: {0} ({1} of 32 characters)',
  'min.gesperrt': 'Stop mining to change the settings.',
  'min.erwartung': 'What to expect',
  'min.deine': 'Your hashrate',
  'min.gemessen': 'measured right now',
  'min.nochNicht': 'not running yet',
  'min.schaetzung': 'At this hashrate you find a block about every {0} on average. That is an average, not a promise. It can be faster or take much longer.',
  'min.schaetzungOhne': 'Once mining is running, this shows how often you find a block on average.',
  'min.messwerte': 'Measurements',
  'min.leistung': 'Hashrate',
  'min.fehler': 'Errors',
  'min.arbeitetAn': 'Working on',
  'min.laeuftSeit': 'Running for',
  'min.funde': 'Blocks found by you',
  'min.fundeZahl': a => `solo · ${a} so far`,
  'min.fundeKeine': 'No block found solo yet.',
  'min.fundeOhneAdresse': 'Enter an address and its finds appear here.',

  // Settings
  'einst.titel': 'Settings',
  'einst.sub': 'The defaults suit most people. You do not have to change anything here.',
  'einst.knoten': 'Node',
  'einst.ordner': 'Data folder',
  'einst.ordnerHinweis': 'The blockchain is stored here.',
  'einst.apiPort': 'Node API port',
  'einst.apiHinweis': 'reachable on this PC only',
  'einst.p2pPort': 'P2P port',
  'einst.p2pHinweis': 'for connections to other nodes',
  'einst.seedHinweis': 'The first contact into the network. After that your node finds further nodes on its own.',
  'einst.geltenNach': 'Folder, ports and seed apply after the node has been restarted.',
  'einst.gespeichert': 'Saved.',
  'einst.neustartNoetig': 'Saved. The new values apply once the node has been restarted.',
  'einst.neuStarten': 'Restart node',
  'einst.neuGestartet': 'The node is running with the new values.',
  'einst.programmTitel': 'Program',
  'einst.knotenSofort': 'Start the node as soon as the program opens',
  'einst.knotenSofortHinweis': 'Otherwise you start it by hand in the overview.',
  'einst.sprache': 'Language',
  'einst.protokoll': 'Log',
  'einst.ueber': 'About',
  'einst.programm': 'Program',
  'einst.netz': 'Network',
  'einst.regeln': 'Rules',
  'einst.fassung': 'Consensus revision {0}',
  'einst.quelltext': 'Source code',

  // First start
  'einr.schritte': 'Steps',
  'einr.s1': 'Node',
  'einr.s3': 'Start',
  'einr.titel': 'Your own YSKAR node',
  'einr.einleitung': 'Node Core downloads the blockchain to this PC and verifies every block itself. You do not have to trust anyone. The defaults suit most people, you can simply click Continue.',
  'einr.ordnerHinweis': 'The blockchain is stored here. It is still small and grows with every block.',
  'einr.firewall': 'On first start Windows asks whether Node Core may access the network. Allow it, otherwise the node cannot find other nodes.',
  'einr.bereit': 'Ready to start',
  'einr.bereitText': 'The node starts on {0}, connects to the network and downloads the blockchain.',
  'einr.starten': 'Start node',

  // ---------------------------------------------------------------- Wallet
  'allg.abbrechen': 'Cancel',
  'zeit.heute': 'Today',
  'zeit.gestern': 'Yesterday',
  'zeit.heuteKurz': 'today',
  'nav.wallet': 'Wallet',
  'kette.du': 'you',
  'einr.s2': 'Wallet',
  'einr.walletDa': 'There is already a wallet on this PC. It stays as it is.',
  'einr.walletSpaeter': 'to be set up later',
  'min.meineWallet': 'My wallet',
  'min.andere': 'Another address',
  'ueb.oeffnen': 'Open',
  'ueb.walletFehlt': 'No wallet on this PC yet. Your mining rewards go into the wallet.',
  'ueb.walletGesperrt': 'Unlock to see balance and history.',

  'wal.titel': 'Wallet',
  'wal.sub': 'Your YSR on this PC. The key never leaves the device.',
  'wal.bereiche': 'Wallet sections',
  'wal.rUebersicht': 'Overview',
  'wal.rSenden': 'Send',
  'wal.rEmpfangen': 'Receive and contacts',
  'wal.rSicherung': 'Backup',
  'wal.sperren': 'Lock',
  'wal.entsperrt': 'unlocked',
  'wal.entsperrtRest': m => `unlocked · locks in ${m} min`,
  'wal.gesperrt': 'locked',

  'wal.einrichten': 'Set up wallet',
  'wal.einrichtenText': 'Your mining rewards go into the wallet. From here you send and receive YSR.',
  'wal.art': 'Kind of setup',
  'wal.neu': 'New wallet',
  'wal.neuText': 'You get 12 new words.',
  'wal.alt': 'Existing wallet',
  'wal.altText': 'With the 12 words from the app.',
  'wal.spaeter': 'Later',
  'wal.spaeterText': 'Just run the node.',
  'wal.spaeterLang': 'The node also runs without a wallet. You can set one up at any time under "Wallet". For mining you then need an address from elsewhere, for example from the app.',
  'wal.deine12': 'Your 12 words',
  'wal.die12': 'The 12 words',
  'wal.woerterWarnung': 'Write the words on paper in this order. They are the only way back to your balance. Nobody can restore them for you.',
  'wal.woerterPlatz': 'twelve words, separated by spaces',
  'wal.woerterZahl': n => `${n} of 12 words`,
  'wal.notiert': 'I have written the 12 words down on paper.',
  'wal.erstNotieren': 'First confirm that you have written down the 12 words.',
  'wal.anlegen': 'Create wallet',
  'wal.wiederherstellen': 'Restore wallet',
  'wal.passwort': 'Password',
  'wal.pwFuerPc': 'Password for this PC',
  'wal.pwNeu': 'New password',
  'wal.pwWiederholen': 'Repeat password',
  'wal.pwRegel': 'At least {0} characters. The longer, the better.',
  'wal.pwKurz': 'Too short: {0} of at least {1} characters.',
  'wal.pwGeht': '{0} characters. Longer would be better.',
  'wal.pwGut': 'good · {0} characters',
  'wal.pwUngleich': 'The two passwords do not match.',

  'wal.gesperrtTitel': 'Wallet locked',
  'wal.gesperrtText': 'Enter your password to see balance and history and to send.',
  'wal.entsperren': 'Unlock',
  'wal.vergessen': 'Forgot your password? Set a new one with the 12 words',
  'wal.vergessenTitel': 'Set a new password',
  'wal.vergessenText': 'Enter the 12 words of this wallet and choose a new password. Other words will not work.',
  'wal.pwSetzen': 'Set password',
  'wal.gesperrtHinweis': 'Node and mining keep running while the wallet is locked. For mining the program only needs your address, not your key. Rewards still arrive.',

  'wal.guthaben': 'Balance',
  'wal.heute': 'today',
  'wal.unterwegs': 'pending',
  'wal.verfuegbar': 'available',
  'wal.adresseKopieren': 'Copy address',
  'wal.empfangen': 'Receive',
  'wal.kontakte': 'Contacts',
  'wal.einnahmen': 'Mining income',
  'wal.sieben': 'last 7 days',
  'wal.ausBloecken': b => `YSR from ${b} ${b === 1 ? 'block' : 'blocks'}`,
  'wal.filter': 'Filter',
  'wal.fAlle': 'All',
  'wal.fEin': 'Incoming',
  'wal.fAus': 'Outgoing',
  'wal.suchfeld': 'Name, address or note',
  'wal.mehr': 'Show older',
  'wal.ausKnoten': 'The history comes from your own node, not from a server.',
  'wal.nochNichts': 'Nothing has happened yet. As soon as something arrives or you send, it appears here.',
  'wal.nichtsPassend': 'No entry matches that.',
  'wal.miningPool': 'Pool mining',
  'wal.miningSolo': 'Solo mining',
  'wal.anteileAus': b => `shares from ${b} ${b === 1 ? 'block' : 'blocks'}`,
  'wal.soloGefunden': b => `${b} ${b === 1 ? 'block' : 'blocks'} found solo`,
  'wal.zuletztBlock': 'latest block {0}',
  'wal.gesendetAn': 'Sent to {0}',
  'wal.empfangenVon': 'Received from {0}',
  'wal.wartetBlock': 'waiting for the next block',
  'wal.notizZeile': 'Note: {0}',
  'wal.gebuehrZeile': 'fee {0}',

  'wal.ueberweisung': 'Transfer',
  'wal.sEmpfaenger': 'Recipient',
  'wal.sBetrag': 'Amount',
  'wal.sPruefen': 'Review',
  'wal.sGesendet': 'Sent',
  'wal.empfaenger': 'Recipient',
  'wal.kontaktWaehlen': 'Choose contact',
  'wal.keineKontakte': 'no contacts',
  'wal.alles': 'Max',
  'wal.verfuegbarZeile': 'Available: {0} YSR',
  'wal.notiz': 'Note',
  'wal.notizHinweis': n => `Stored publicly in the blockchain, the recipient sees it too. ${n} of 32 bytes.`,
  'wal.tempo': 'Speed',
  'wal.langsam': 'slow',
  'wal.normal': 'normal',
  'wal.schnell': 'fast',
  'wal.tempoHinweis': 'The network is busy right now. Paying more gets you into a block sooner.',
  'wal.pruefen': 'Review',
  'wal.pruefenTitel': 'Review and send',
  'wal.pruefenLeer': 'Enter recipient and amount on the left and click Review. Nothing is sent without your password.',
  'wal.anAdresse': 'To this address',
  'wal.anName': 'To {0}',
  'wal.neueAdresse': 'New address.',
  'wal.neueAdresseText': 'You have never sent there before. Compare it character by character with the address you were given.',
  'wal.netzgebuehr': 'Network fee',
  'wal.naechsterBlock': 'next block',
  'wal.inBloecken': b => `in about ${b} blocks`,
  'wal.gesamt': 'Total',
  'wal.danach': 'Available afterwards',
  'wal.jetztSenden': 'Send now',
  'wal.endgueltig': 'A transfer cannot be taken back. Your node passes it straight to the network.',
  'wal.gesendetTitel': 'Sent',
  'wal.gesendetText': p => `The transfer is on its way and was announced to ${p} ${p === 1 ? 'peer' : 'peers'}. It is confirmed with the next block.`,
  'wal.zurUebersicht': 'Back to overview',
  'wal.weitere': 'Another transfer',

  'wal.qrAlt': 'QR code with your address',
  'wal.deineAdresse': 'Your address',
  'wal.adresseHinweis': 'You may give this address to anyone. It is the same as in the YSKAR app if you use the same 12 words there.',
  'wal.anfordern': 'Request an amount',
  'wal.anfordernHinweis': 'The QR code then contains address and amount. Whoever scans it with the app does not have to type anything.',
  'wal.kGespeichert': k => `${k} saved · on this PC only`,
  'wal.kKeine': 'No contacts yet. A contact is a name for an address.',
  'wal.kBearbeiten': 'Edit',
  'wal.kEntfernen': 'Remove contact {0}',
  'wal.kHinzu': 'Add a contact',
  'wal.kName': 'Name',
  'wal.kNamePlatz': 'for example Mara',
  'wal.kGespeichertMeldung': 'Contact saved.',

  'wal.die12Text': 'The 12 words are your wallet. If the PC is lost, you restore everything with them.',
  'wal.verdeckt': 'The 12 words, hidden',
  'wal.woerterZeigen': 'Show words',
  'wal.woerterVerdecken': 'Hide words',
  'wal.woerterGeheim': 'Whoever knows the 12 words can spend your balance. Write them on paper. No photo, no cloud, and never give them to anyone who asks.',
  'wal.inApp': 'The same wallet in the app',
  'wal.inAppText': 'With the same 12 words you also open this wallet in the YSKAR app on your phone. The balance is in the blockchain, not in a program. Both therefore show the same state.',
  'wal.pwAendern': 'Change password',
  'wal.pwAktuell': 'Current password',
  'wal.pwAendernHinweis': 'The password protects the wallet file on this PC. It does not replace the 12 words.',
  'wal.pwGeaendert': 'The password has been changed.',
  'wal.sperre': 'Lock',
  'wal.sperreNach': 'Lock automatically after',
  'wal.minuten': m => `${m} minutes`,
  'wal.nie': 'never',
  'wal.pwVorSenden': 'Password before every transfer',
  'wal.pwVorSendenHinweis': 'Even while the wallet is unlocked.',
  'wal.immerAn': 'always on',
  'wal.datei': 'Wallet file',
  'wal.dateiHinweis': 'Encrypted with AES-256-GCM. The key is derived from your password (PBKDF2, 400,000 rounds). The longer the password, the better the protection.',
  'wal.entfernenText': 'Removes the wallet from this PC. The balance stays in the blockchain and can be reached again with the 12 words. Without the words it is lost.',
  'wal.entfernen': 'Remove wallet',
  // Pool mining
  'pool.pool': 'Pool',
  'pool.hinweis': 'Pool: The reward of every block is split by the work done and paid out directly in the block. Smaller amounts, but regular.',
  'pool.waehlen': 'Choose a pool',
  'pool.listeHinweis': 'the same list as in the app',
  'pool.laedt': 'Asking the pools …',
  'pool.listeLeer': 'The pool list is not available right now.',
  'pool.eigen': 'Your own pool address',
  'pool.eigenKurz': 'own address',
  'pool.pruefen': 'Check',
  'pool.eigenUngueltig': 'That is not a pool address. Example: pool.example.org',
  'pool.gewaehlt': 'selected',
  'pool.voll': 'full',
  'pool.aus': 'not responding',
  'pool.keinPool': 'no pool',
  'pool.ausText': 'Nobody is answering at this address right now.',
  'pool.keinPoolText': 'No pool is running at this address.',
  'pool.ohneZahlen': 'Older version: the pool reports no numbers. Whether it accepts you shows when you start.',
  'pool.miner': 'Miners',
  'pool.bloecke': 'Blocks',
  'pool.gebuehr': 'Fee',
  'pool.belegtAlt': '{0} of {1} places taken',
  'pool.verbindung': 'Connection to the pool',
  'pool.verbunden': 'connected',
  'pool.gestoert': 'connection trouble',
  'pool.getrennt': 'not connected',
  'pool.minerImPool': 'Miners in the pool',
  'pool.angenommen': 'Accepted shares',
  'pool.abgelehnt': 'Rejected shares',
  'pool.anteil': 'Your part of the hashrate',
  'pool.rund': 'about {0} %',
  'pool.auszahlung': 'Last payout',
  'pool.fehlerZuletzt': 'Latest: {0}',
  'pool.nieSolo': 'If the pool is full or no longer accepts you, mining stops and tells you why. It never silently continues solo.',
  'pool.gesamtSeit': 'Total, for {0}',
  'pool.verlaufLeer': 'The chart starts after the first measurements.',
  'pool.verlaufAlt': 'Hashrate over the last {0}, between {1} and {2}',
  'pool.vor': '{0} ago',
  'pool.jetzt': 'now',
  'pool.endeTitel': 'Mining in the pool {0} has ended.',
  'pool.ende.pool_full': 'The pool is full: all places are taken.',
  'pool.ende.pool_unavailable': 'The node no longer runs a pool.',
  'pool.ende.bad_address': 'The pool does not accept this address.',
  'pool.fehler.pool_fehlt': 'Please choose a pool first.',
  'pool.fehler.pool_aus': 'The pool is not responding. Mining was not started.',
  'pool.fehler.pool_unavailable': 'No pool is running at this address.',
  'pool.fehler.pool_full': 'The pool is full: all places are taken. Choose another pool or try again later.',
  'pool.fehler.bad_address': 'The pool does not accept this address.',
};
